#!/usr/bin/env python3
# -*- coding: utf-8 -*-

########################################################################
# marky Markdown Preprocessor ###########################################
########################################################################

# Quick Make Example Project
############################
#
#  > mkdir project
#  > cp /path/to/marky.py project
#  > cd project
#  > chmod +x marky.py
#  > ./marky.py --init
#  > make scan html-all pdf-all httpd
#
# Open: project/pdf/*.pdf
# Goto: http://localhost:8000/

########################################################################

import sys
import argparse
import glob
import os
import base64
import yaml

########################################################################

if not sys.version_info.major == 3 and sys.version_info.minor >= 6:
	try:
		raise ValueError("marky requires Python 3.6 or higher.")
	except Exception as ex:
		print("# ERROR", type(ex), str(ex))
		sys.exit(1)

########################################################################

_MARKY_VERSION = (0, 9)

########################################################################
# SECTION IS AUTO-PACKAGED USING ./marky.py --pack --force
########################################################################
###!!!:::marky_pack_data:::!!!###
pack_Makefile = '''
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjCgouUEhPTlk6IGhlbHAKaGVscDoKCSMgbWFya3kgREVQRU5E
RU5DSUVTCgkjIyMjIyMjIyMjIyMjIyMjIyMjIwoJIyAqIHBhbmRvYyA+PSAyLjEwCgkjICog
cGlwIGluc3RhbGwgcGFuZG9jLWZpZ25vcwoJIyAqIHBpcCBpbnN0YWxsIHBhbmRvYy1lcW5v
cwoJIyAqIHBpcCBpbnN0YWxsIHBhbmRvYy1zZWNub3MKCSMgKiBwaXAgaW5zdGFsbCBwYW5k
b2MtdGFibGVub3MKCSMgKiBwaXAgaW5zdGFsbCBwYW5kb2MteG5vcwoJIyAqIHBpcCBpbnN0
YWxsIHB5eWFtbAoJIwoJIyBBVFRFTlRJT04KCSMjIyMjIyMjIyMjCgkjIEFsbCBmaWxlcyBp
biBgYnVpbGQvKi5tZGAgYW5kIGBodG1sLyouaHRtbGAgYXJlIGF1dG8tZ2VuZXJhdGVkIQoJ
IyBVc2VyIGZpbGVzIGAqLm1kYCBoYXZlIHRvIGJlIHBsYWNlZCBpbiBgbWQvKi5tZGAhCgkj
IGBtYWtlIGNsZWFuYCBkZWxldGVzIGFsbCBmaWxlcyBpbiBgYnVpbGQvYCwgYGh0bWwvYCBh
bmQgYHBkZi9gLgoJIwoJIyBtYXJreSBVVElMUwoJIyMjIyMjIyMjIyMjIwoJIyAqIG1ha2Ug
aGVscCAgICAgICAgICAgIC0gc2hvdyB0aGlzICpIZWxwIE1lc3NhZ2UqCgkjICogbWFrZSB0
cmVlICAgICAgICAgICAgLSBzaG93IHRoZSAqUHJvamVjdCBUcmVlKgoJIyAqIG1ha2UgaHR0
cGQgICAgICAgICAgIC0gcnVuIHB5dGhvbiAtbSBodHRwZC5zZXJ2ZXIgaW4gYGh0bWwvYAoJ
IyAqIG1ha2UgY2xlYW4gICAgICAgICAgIC0gZGVsZXRlOiBgYnVpbGQvKmAsIGBodG1sLypg
LCBgcGRmLypgCgkjICogbWFrZSBzY2FuICAgICAgICAgICAgLSBidWlsZCBtYWtlIGRlcHM6
IGBidWlsZC8qLm1ha2VgCgkjICogbWFrZSBsaXN0ICAgICAgICAgICAgLSBsaXN0IGFsbCBz
Y2FubmVkIGZpbGVzIGFuZCB0YXJnZXRzCgkjCgkjIG1hcmt5IEJVSUxEIEFMTAoJIyMjIyMj
IyMjIyMjIyMjIyMKCSMgKiBtYWtlIGJ1aWxkICAgICAgICAgICAtPiBgYnVpbGQvKi57aHRt
bCxwZGZ9Lm1kYAoJIyAqIG1ha2UgdGV4ICAgICAgICAgICAgIC0+IGBidWlsZC8qLnRleGAK
CSMgKiBtYWtlIGh0bWwgICAgICAgICAgICAtPiBgaHRtbC8qLmh0bWxgCgkjICogbWFrZSBw
ZGYgICAgICAgICAgICAgLT4gYHBkZi8qLnBkZmAKCSMgKiBtYWtlIGFsbCAgICAgICAgICAg
ICAtPiBgaHRtbC8qLmh0bWxgLCBgcGRmLyoucGRmYAoJIwoJIyBtYXJreSBCVUlMRCBGSUxF
CgkjIyMjIyMjIyMjIyMjIyMjIyMKCSMgKiBtYWtlIGJ1aWxkL2ZpbGUgICAgICAtPiBgYnVp
bGQvZmlsZS57aHRtbCxwZGZ9Lm1kYAoJIyAqIG1ha2UgYnVpbGQvZmlsZS50ZXggIC0+IGBi
dWlsZC9maWxlLnRleGAKCSMgKiBtYWtlIGh0bWwvZmlsZSAgICAgICAtPiBgaHRtbC9maWxl
Lmh0bWxgCgkjICogbWFrZSBwZGYvZmlsZSAgICAgICAgLT4gYHBkZi9wZGYuaHRtbGAKCSMK
CSMgRVhBTVBMRQoJIyMjIyMjIyMjCgkjIDEuIHJ1biBgbWFrZSBzY2FuIGh0bWwvZmlsZS5o
dG1sIGh0dHBkYDoKCSMgICAgKiBnZW5lcmF0ZSBgYnVpbGQvZmlsZS5tYWtlYAoJIyAgICAq
IHRyYW5zZm9ybSBgbWQvZmlsZS5tZGAgLT4gYGh0bWwvZmlsZS5odG1sYAoJIyAgICAqIHN0
YXJ0IGEgcHl0aG9uIGh0dHBkIHNlcnZlciBpbiBgaHRtbGAKCSMgMi4gcnVuIGBtYWtlIHNj
YW4gcGRmL2ZpbGUucGRmYAoJIyAgICAqIGdlbmVyYXRlIGBidWlsZC9maWxlLm1ha2VgCgkj
ICAgICogdHJhbnNmb3JtIGBtZC9maWxlLm1kYCAtPiBgcGRmL2ZpbGUucGRmYAoJIwoKLlBI
T05ZOiB0cmVlCnRyZWU6CgkjIFBST0pFQ1QgVFJFRQoJIyMjIyMjIyMjIyMjIyMKCSMgPHdv
cmtpbmdfZGlyPgoJIyB8LSBtYXJreS5weSAgICAgICAgICAgIC0gbWFya3kgZXhlY3V0YWJs
ZQoJIyB8LSBNYWtlZmlsZSAgICAgICAgKCopIC0gbWFya3kgTWFrZWZpbGUKCSMgfC0gcGFu
ZG9jLXJ1biAgICAgICgqKSAtIHBhbmRvYyB3cmFwcGVyCgkjIHwtIG1kLyAgICAgICAgICAg
ICAoKikgLSB1c2VyIE1hcmtkb3duIGRpcgoJIyB8ICB8LSAqLm1kICAgICAgICAgKCopIC0g
dXNlciBNYXJrZG93biB0ZXh0CgkjIHwtIGRhdGEvICAgICAgICAgICAoKikgLSB1c2VyIGRh
dGEgZGlyCgkjIHwgIHwtICouKiAgICAgICAgICAgICAgICB1c2VyIGRhdGEgZmlsZXMKCSMg
fC0gYnVpbGQvICAgICAgICAgICgqKSAtIGJ1aWxkIE1hcmtkb3duIGRpcgoJIyB8ICB8LSAq
LnB5ICAgICAgICAgKCopIC0gTWFya2Rvd24gbWFya3kgY29kZQoJIyB8ICB8LSAqLm1ha2Ug
ICAgICAgKCopIC0gTWFrZWZpbGUgcnVsZXMKCSMgfCAgfC0gKi5odG1sLm1kICAgICgqKSAt
IE1hcmtkb3duIGZvciBodG1sIGZvcm1hdAoJIyB8ICB8LSAqLnBkZi5tZCAgICAgKCopIC0g
TWFya2Rvd24gZm9yIHBkZiBmb3JtYXQKCSMgfC0gaHRtbC8qLmh0bWwgICAgICgqKSAtIHJl
bmRlcmVkIGh0bWwgZGlyCgkjIHwtIHBkZi8qLnBkZiAgICAgICAoKikgLSByZW5kZXJlZCBw
ZGYgZGlyCgkjCgkjICgqKSBkaXJlY3Rvcmllcy9maWxlcyBhcmUgYXV0by1nZW5lcmF0ZWQg
dXNpbmcKCSMgICAgYC4vbWFya3kucHkgLS1pbml0YCBhbmQgYG1ha2Ugc2NhbsK0CgkjCgou
UEhPTlk6IGNsZWFuCmNsZWFuOgoJcm0gLXJmIC4vYnVpbGQvKiAuL2h0bWwvKiAuL3BkZi8q
CgouUEhPTlk6IGh0dHBkCmh0dHBkOgoJY2QgaHRtbCAmJiBweXRob24gLW0gaHR0cC5zZXJ2
ZXIKCi5QSE9OWTogc2NhbgpzY2FuOgoJLi9tYXJreS5weSAtLXNjYW4KCiMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIwoKYWxsX21kOj0KYWxsX2J1aWxkOj0KYWxsX2h0bWw6PQphbGxfcGRmOj0KYWxs
X3RleDo9CgotaW5jbHVkZSBidWlsZC8qLm1ha2UgYnVpbGQvKiovKi5tYWtlCgojIyMjIyMj
IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj
IyMjIyMjIyMjIyMKCi5QSE9OWTogbGluawpidWlsZDogJChhbGxfYnVpbGQpCgouUEhPTlk6
IGh0bWwKaHRtbDogJChhbGxfaHRtbCkKCi5QSE9OWTogcGRmCnBkZjogJChhbGxfcGRmKQoK
LlBIT05ZOiB0ZXgKdGV4OiAkKGFsbF90ZXgpCgouUEhPTlk6IGFsbAphbGw6IGh0bWwgcGRm
CgouUEhPTlk6IGxpc3QKbGlzdDoKCSMgbWFya3kgVEFSR0VUUwoJIyMjIyMjIyMjIyMjIyMj
CgkjICogYG1ha2Ugc2NhbmAgLS0gRklMRVM6JChhbGxfbWQpCgkjICogYG1ha2UgYnVpbGRg
IC0tIGBtYWtlJChhbGxfYnVpbGQpYAoJIyAqIGBtYWtlIGh0bWxgIC0tIGBtYWtlJChhbGxf
aHRtbClgCgkjICogYG1ha2UgcGRmYCAtLSBgbWFrZSQoYWxsX3BkZilgCgkjICogYG1ha2Ug
dGV4YCAtLSBgbWFrZSQoYWxsX3RleClgCgkjCg==
'''
pack_pandoc_run = '''
IyEvYmluL2Jhc2gKClsgJCMgPT0gMCBdICYmIGVjaG8gIiIiCiMgVXNhZ2U6ICQwOiA8Rk9S
TUFUPiA8SU5GSUxFPiA8T1VURklMRT4KIyBFeGFtcGxlOgojICQwIGh0bWwgYnVpbGQvZmls
ZS5odG1sLm1kIGh0bWwvZmlsZS5odG1sCiMgJDAgcGRmIGJ1aWxkL2ZpbGUucGRmLm1kIHBk
Zi9maWxlLnBkZgoiIiIgJiYgZXhpdCAxCgpQQU5ET0M9cGFuZG9jCgpNREVYVD1cCmFsbF9z
eW1ib2xzX2VzY2FwYWJsZStcCmludHJhd29yZF91bmRlcnNjb3JlcytcCmVzY2FwZWRfbGlu
ZV9icmVha3MrXApzcGFjZV9pbl9hdHhfaGVhZGVyK1wKbGlzdHNfd2l0aG91dF9wcmVjZWRp
bmdfYmxhbmtsaW5lK1wKaW5saW5lX2NvZGVfYXR0cmlidXRlcytcCnN0cmlrZW91dCtcCnlh
bWxfbWV0YWRhdGFfYmxvY2srXApwaXBlX3RhYmxlcytcCmxpbmVfYmxvY2tzK1wKaW1wbGlj
aXRfZmlndXJlcytcCmFiYnJldmlhdGlvbnMrXAppbmxpbmVfbm90ZXMKClBET1BUPSIiIgot
LXRhYmxlLW9mLWNvbnRlbnRzCi0tbnVtYmVyLXNlY3Rpb25zCiIiIgoKaWYgWyAkMSA9PSBo
dG1sIF0gOyB0aGVuCiRQQU5ET0MgIiQyIiBcCi0tZmlsdGVyIHBhbmRvYy14bm9zIFwKLS1j
aXRlcHJvYyBcCi0tZnJvbT1tYXJrZG93bityYXdfaHRtbCskTURFWFQgXAotLXRvPWh0bWw1
IFwKLS1zZWxmLWNvbnRhaW5lZCBcCi0tb3V0cHV0PSIkMyIgXAotLXJlc291cmNlLXBhdGg9
Ii4vYnVpbGQvIiBcCiRQRE9QVApmaQoKaWYgWyAkMSA9PSBwZGYgXSA7IHRoZW4KJFBBTkRP
QyAiJDIiIFwKLS1maWx0ZXIgcGFuZG9jLXhub3MgXAotLWNpdGVwcm9jIFwKLS1mcm9tPW1h
cmtkb3duK3Jhd190ZXgrJE1ERVhUIFwKLS10bz1sYXRleCBcCi0tb3V0cHV0PSIkMyIgXAot
LXJlc291cmNlLXBhdGg9Ii4vYnVpbGQvIiBcCi0tcGRmLWVuZ2luZT14ZWxhdGV4IFwKJFBE
T1BUCmZpCgppZiBbICQxID09IHRleCBdIDsgdGhlbgokUEFORE9DICIkMiIgXAotLWZpbHRl
ciBwYW5kb2MteG5vcyBcCi0tY2l0ZXByb2MgXAotLWZyb209bWFya2Rvd24rcmF3X3RleCsk
TURFWFQgXAotLXRvPWxhdGV4IFwKLS1vdXRwdXQ9IiQzIiBcCi0tcmVzb3VyY2UtcGF0aD0i
Li9idWlsZC8iIFwKJFBET1BUCmZpCg==
'''
pack_marky_md = '''
LS0tCnRpdGxlOiAiYG1hcmt5YCBEb2N1bWVudGF0aW9uICIKdGl0bGUtLXBkZjogIi0tIGBw
ZGZgIgp0aXRsZS0taHRtbDogIi0tIGBodG1sYCIKYmlibGlvZ3JhcGh5OiBkYXRhL21hcmt5
LmJpYgpoZWFkZXItaW5jbHVkZXMtLXBkZjogPgogICBcaHlwZXJzZXR1cHtjb2xvcmxpbmtz
PWZhbHNlLAogICBhbGxib3JkZXJjb2xvcnM9ezAgMCAwfSwKICAgcGRmYm9yZGVyc3R5bGU9
ey9TL1UvVyAxfX0KaGVhZGVyLWluY2x1ZGVzLS1odG1sOiA+CiAgIDxzdHlsZT4qIHsgYm94
LXNpemluZzogYm9yZGVyLWJveDsgfTwvc3R5bGU+Cnhub3MtY2xldmVyZWY6IHRydWUKeG5v
cy1jYXBpdGFsaXNlOiB0cnVlCmZvbnRzaXplOiAxMXB0CgotLS0KPD8KY29sID0gZm10Y29k
ZSgKCWh0bWw9IjxzcGFuIHN0eWxlPSdjb2xvcjp7MX07Jz57MH08L3NwYW4+IiwKCXBkZj1y
Ilx0ZXh0Y29sb3J7e3sxfX19e3t7MH19fSIKKQpkZWYgdGV4dF9wcm9jKGNtZCwgY3JvcD1U
cnVlKToKCWltcG9ydCBzdWJwcm9jZXNzIGFzIHNwCgl0ZXh0ID0gIiIKCWZvciBpIGluIHNw
LmNoZWNrX291dHB1dChjbWQuc3BsaXQoKSkuZGVjb2RlKCJ1dGYtOCIpLnNwbGl0KCJcbiIp
OgoJCWlmIG5vdCBjcm9wOgoJCQl0ZXh0ICs9IGkgKyAiXG4iCgkJZWxpZiBpLnN0YXJ0c3dp
dGgoIiMgIik6CgkJCXRleHQgKz0gaVsyOl0gKyAiXG4iCgkJZWxpZiBpID09ICIjIjoKCQkJ
dGV4dCArPSAiXG4iCgkJZWxpZiBpLnN0YXJ0c3dpdGgoIiMiKToKCQkJdGV4dCArPSBpICsg
IlxuIgoJcmV0dXJuIHRleHQKdmVyc2lvbiA9IHRleHRfcHJvYygicHl0aG9uIG1hcmt5LnB5
IC0tdmVyc2lvbiIsIGNyb3A9RmFsc2UpLnN0cmlwKCkKPz4KLS0tCgo+ICoqQWJzdHJhY3Qq
KiAtLSBgbWFya3lgIGlzIGEgcHJlcHJvY2Vzc29yIHdpdGggYW4gZWFzeSBhbmQgaW50dWl0
aXZlCj4gc3ludGF4IGZvciBleGVjdXRpb24gb2YgZW1iZWRkZWQge3tjb2woInB5aG9uIiwi
Ymx1ZSIpfX0gY29kZSBkdXJpbmcgcmVuZGVyaW5nCj4gYGh0bWxgIGFuZCBgcGRmYCBkb2N1
bWVudHMgZnJvbSBNYXJrZG93biB0ZXh0Lgo+IFRoaXMgZG9jdW1lbnQgaXMgY3JlYXRlZCB1
c2luZyBgbWFya3lgLCB2ZXJzaW9uICp7e3ZlcnNpb259fSouCj4gRm9yIG1vcmUgaW5mb3Jt
YXRpb24gcGxlYXNlIHJlZmVyIHRvIHRoZQo+IFtgbWFya3lgIHJlcG9zaXRvcnldKGh0dHBz
Oi8vZ2l0aHViLmNvbS9sZWhtYW5uNy9tYXJreSkuCgotLS0KCiMgYG1hcmt5YCBEeW5hbWlj
IE1hcmtkb3duCgpgbWFya3lgIGlzIGEgTWFya2Rvd24gcHJlcHJvY2Vzc29yIHdoaWNoIHRy
YW5zZm9ybXMgYSBNYXJrZG93biBkb2N1bWVudAp1c2luZyBweXRob24uIGBtYXJreWAgaW1w
bGVtZW50cyB0aHJlZSBzdGF0ZW1lbnRzIHdpdGggZXh0cmVtZWx5IGVhc3kKYW5kIGludHVp
dGl2ZSBzeW50YXgsIHdoaWNoIGFyZSBlbWJlZGRlZCBkaXJlY3RseSBpbiB0aGUgTWFya2Rv
d24gdGV4dDoKCjEuIGA8XD8uLi4/XD5gOiBQeXRob24gY29kZSBibG9jay4KMi4gYHtcey4u
Ln1cfWA6IGBmYC1zdHJpbmcgb3V0cHV0IGludG8gTWFya2Rvd24uCjMuIGBfX18oKWA6IEZ1
bmN0aW9uIGZvciBvdXRwdXQgaW50byBNYXJrZG93bi4KClVzaW5nIGA8XD8uLi4/XD5gIGFu
ZCBge1x7Li4ufVx9YCBweXRob24gcHJvY2Vzc2luZyBhbmQgYGZgLXN0cmluZyBvdXRwdXQK
aXMgZW1iZWRkZWQgZGlyZWN0bHkgaW5zaWRlIHRoZSBNYXJrZG93biB0ZXh0LiBVc2luZyB0
aGUgYF9fXygpYApmdW5jdGlvbiB0ZXh0IGlzIGdlbmVyYXRlZCBmcm9tIHB5dGhvbiBhbGdv
cml0aG1zIGFuZApkeW5hbWljYWxseSBpbnNlcnRlZCBpbnRvIHRoZSByZXN1bHRpbmcgTWFy
a2Rvd24uCgpUaGUgZm9sbG93aW5nIGV4YW1wbGUgY2FuIGJlIHByb2R1Y2VkIGJ5IGp1c3Qg
Y2FsbGluZwpgbWFrZSBwZGYvZmlsZWAgb3IgYG1ha2UgaHRtbC9maWxlYC4KCiMjIyMgRXhh
bXBsZTogYG1kL2ZpbGUubWRgIHstfQpgYGBtYXJrZG93bgotLS0KdGl0bGU6IEFuIEV4YW1w
bGUKLS0tCjxcPwpkZWYgY2FwX2ZpcnN0KHgpOgoJcmV0dXJuICIgIi5qb2luKFtpWzBdLnVw
cGVyKCkgKyBpWzE6XSBmb3IgaSBpbiBpLnNwbGl0KCldKQpmb3IgaSBpbiBbInZlcnkiLCAi
bm90IHNvIl06Cgk/XD4KKip7XHtjYXBfZmlyc3QoaSl9XH0gU2VjdGlvbioqCgpUbyBkYXkg
aXMgYSB7XHtpfVx9IHZlcnkgbmljZSBkYXkuClRoZSBzdW4gaXMgc2hpbmluZyB7XHtpfVx9
IGJyaWdodCBhbmQKdGhlIGJpcmRzIGFyZSBzaW5naW5nIHtce2l9XH0gbG91ZCBhbmQKZmx5
IHtce2l9XH0gaGlnaCBpbiB0aGUge1x7aX1cfSBibHVlIHNreS4KCTxcPwo/XD4KYGBgCiMj
IyMgT3V0cHV0IGBidWlsZC9maWxlLm1kYCB7LX0KYGBgbWFya2Rvd24KLS0tCnRpdGxlOiBB
biBFeGFtcGxlCi0tLQo8PwpkZWYgY2FwX2ZpcnN0KHgpOgoJcmV0dXJuICIgIi5qb2luKFtp
WzBdLnVwcGVyKCkgKyBpWzE6XSBmb3IgaSBpbiBpLnNwbGl0KCldKQpmb3IgaSBpbiBbInZl
cnkiLCAibm90IHNvIl06Cgk/PgoqKnt7Y2FwX2ZpcnN0KGkpfX0gU2VjdGlvbioqCgpUbyBk
YXkgaXMgYSB7e2l9fSB2ZXJ5IG5pY2UgZGF5LgpUaGUgc3VuIGlzIHNoaW5pbmcge3tpfX0g
YnJpZ2h0IGFuZAp0aGUgYmlyZHMgYXJlIHNpbmdpbmcge3tpfX0gbG91ZCBhbmQKZmx5IHt7
aX19IGhpZ2ggaW4gdGhlIHt7aX19IGJsdWUgc2t5LgoJPD8KPz4KYGBgCgojIEhvdyBkb2Vz
IGBtYXJreWAgd29yayBpbnRlcm5hbGx5PwoKYG1hcmt5YCB1c2VzIGFuIGV4dHJlbWVseSBz
aW1wbGUgbWVjaGFuaXNtIGZvciBnZW5lcmF0aW5nIGEgcHl0aG9uIHByb2dyYW1tCmZyb20g
dGhlIE1hcmtkb3duIHRleHQuIFVzaW5nIHRoZSBgPFw/Li4uP1w+YCBhbmQgYHtcey4uLn1c
fWAgc3RhdGVtZW50LApQeXRob24gY29kZSBpcyBlbWJlZGRlZCBpbnRvIHRoZSBNYXJrZG93
biB0ZXh0IGFuZCB0cmFuc2xhdGVkIGludG8gYSBzZXJpZXMKb2YgY2FsbHMgdG8gdGhlIGBf
X18oKWAgZnVuY3Rpb24gdXNpbmcgYGZgLXN0cmluZ3MgYXMgYXJndW1lbnRzLCB3aGVyZQpw
eXRob24gdmFyaWFibGVzIGFyZSByZWZlcmVuY2VkLiBUaGlzIHJlc3VsdHMgaW50byBhIHB5
dGhvbiBwcm9ncmFtCndoaWNoIGNhbiBnZW5lcmF0ZSBNYXJrZG93biB0ZXh0IGFsZ29yaXRo
bWljYWxseS4KCiMjIyMgRXhhbXBsZTogYG1kL2ZpbGUubWRgIHstfQpgYGBwaHAKKiBUaGlz
IGlzIHtmaXJzdH0uIDxcPwp4ID0gMSAjIHRoaXMgaXMgY29kZQpmb3IgaSBpbiByYW5nZSgz
KToKCWlmIHg6CgkJP1w+Cntce2krMX1cfS4gVGhlIHZhbHVlIGlzIHtce1x7eH1cfVx9Lgo8
XD8KCWVsc2U6CgkJP1w+e1x7aSsxfVx9LiBUaGUgdmFsdWUgaXMgemVyby4KPFw/Cgl4ID0g
MAo/XD4qIFRoaXMgaXMgbGFzdC4KYGBgClRoZSBmaWxlIHByb2R1Y2VzIHRoZSBmb2xsb3dp
bmcgTWFya2Rvd24gb3V0cHV0LgoKIyMjIyBPdXRwdXQ6IE1hcmtkb3duIHstfQpgYGBiYXNo
CiogVGhpcyBpcyB7Zmlyc3R9LiA8Pwp4ID0gMSAjIHRoaXMgaXMgY29kZQpmb3IgaSBpbiBy
YW5nZSgzKToKCWlmIHg6CgkJPz4Ke3tpKzF9fS4gVGhlIHZhbHVlIGlzIHt7e3h9fX0uCjw/
CgllbHNlOgoJCT8+e3tpKzF9fS4gVGhlIHZhbHVlIGlzIHplcm8uCjw/Cgl4ID0gMAo/Piog
VGhpcyBpcyBsYXN0LgpgYGAKCmBtYXJreWAgdHJhbnNmb3JtcyB0aGUgTWFya2Rvd24gaW50
byBQeXRob24gc291cmNlIGNvZGUuCkV4ZWN1dGlvbiBvZiB0aGUgUHl0aG9uIHNvdXJjZSBj
b2RlIHlpZWxkcyB0aGUgbmV3IE1hcmtkb3duIHRleHQuCgojIyMjIE91dHB1dDogYGJ1aWxk
L2ZpbGUucHlgIHstfQpgYGBweXRob24KX19fKHJmIiIiKiBUaGlzIGlzIHtce2ZpcnN0fVx9
LiAiIiIsIF9fXyk7CnggPSAxICMgdGhpcyBpcyBjb2RlCmZvciBpIGluIHJhbmdlKDMpOgoJ
aWYgeDoKCQlfX18ocmYiIiIKe2krMX0uIFRoZSB2YWx1ZSBpcyB7XHtce3h9XH1cfS4KIiIi
LCBfX18pOwoJZWxzZToKCQlfX18ocmYiIiJ7aSsxfS4gVGhlIHZhbHVlIGlzIHplcm8uCiIi
IiwgX19fKTsKCXggPSAwCl9fXyhyZiIiIiogVGhpcyBpcyBsYXN0LgoiIiIsIF9fXyk7CmBg
YAoKIyBRdWljayBTdGFydAoKIyMgYG1hcmt5YCBEZXBlbmRlbmNpZXMKCmBtYXJreWAgZGVw
ZW5kcyBvbiBgcGFuZG9jYCBhbmQgYHB5eWFtbGAuIGBwYW5kb2NgIGlzIHVzZWQgZm9yIHJl
bmRlcmluZwp0aGUgTWFya2Rvd24gaW50byBgaHRtbGAgYW5kIGBwZGZgLiBgbWFya3lgIHVz
ZXMKW3BhbmRvY10oaHR0cHM6Ly93d3cucGFuZG9jLm9yZy8pIGZvciByZW5kZXJpbmcgYGh0
bWxgIGFuZCBgcGRmYC4KYHBhbmRvYz49Mi4xMGAgcmVsZWFzZXMgY2FuIGJlIGZvdW5kClto
ZXJlXShodHRwczovL2dpdGh1Yi5jb20vamdtL3BhbmRvYy9yZWxlYXNlcykuClRoZSBvdGhl
ciBwYWNrYWdlcyBjYW4gYmUgaW5zdGFsbGVkIHdpdGggYHBpcGAuCgpgYGBiYXNoCnBpcCBp
bnN0YWxsIHBhbmRvYy1maWdub3MKcGlwIGluc3RhbGwgcGFuZG9jLWVxbm9zCnBpcCBpbnN0
YWxsIHBhbmRvYy1zZWNub3MKcGlwIGluc3RhbGwgcGFuZG9jLXRhYmxlbm9zCnBpcCBpbnN0
YWxsIHBhbmRvYy14bm9zCnBpcCBpbnN0YWxsIHB5eWFtbApgYGAKCiMjIGBtYXJreWAgV29y
a2Zsb3cKCldvcmtmbG93IGZvciBjcmVhdGluZyBgaHRtbGAgb3IgYHBkZmAgdXNpbmcgYG1h
cmt5YCBieQppbnZvY2F0aW9uIG9mIGBtYWtlIHNjYW4gYWxsYC4KCip3cml0ZSogICAgIHwt
PnwqYnVpbGQqICAgICAgICAgICAgIHwtPnwqcmVuZGVyKgotLS0tLS0tLS0tLS18LS18LS0t
LS0tLS0tLS0tLS0tLS0tLS18LS18LS0tLS0tLS0tLS0tLS0tLQpgbWQvZmlsZS5tZGB8LT58
YGJ1aWxkL2ZpbGUuaHRtbC5tZGB8LT58YGh0bWwvZmlsZS5odG1sYAogICAgICAgICAgIC58
LT58YGJ1aWxkL2ZpbGUucGRmLm1kYCB8LT58YHBkZi9maWxlLnBkZmAKCjEuICoqd3JpdGUq
KjogdXNlciB3cml0ZXMgYSBNYXJrZG93biB0ZXh0IGZpbGUgYW5kIHBsYWNlcyBpdCBpbiBg
bWQvKi5tZGAKZGlyZWN0b3J5IHdpdGggdGhlIGV4dGVuc2lvbiBgLm1kYC4KMi4gKipidWls
ZCoqOiBtYXJreWAgdHJhbnNmb3JtcyB0aGUgZmlsZXMgaW4gYG1kLyoubWRgIGludG8gcmVn
dWxhciBNYXJrZG93biB0ZXh0CmFuZCBwbGFjZXMgdGhlIHRyYW5zZm9ybWVkIGZpbGVzIGlu
IGBidWlsZC9gLgozLiAqKnJlbmRlcioqOiB0aGUgcmVndWxhciBNYXJrZG93biB0ZXh0IGlu
IHRoZSBmaWxlcyBgYnVpbGQvKi5tZGAgaXMgcmVuZGVyZWQgaW50bwpgaHRtbGAgYW5kIGBw
ZGZgIHVzaW5nIGBwYW5kb2NgLgoKVGhlIHRocmVlIHN0ZXBzIGFyZSBpbXBsZW1lbnRlZCBp
biBhIE1ha2VmaWxlLgoKIyMgRG93bmxvYWQgYW5kIEluaXRpYWxpemUKCmBtYXJreWAgaXMg
c3VwcGxpZWQgYXMgYSBzaW5nbGUtZmlsZSBzY3JpcHQgd2hpY2ggYXV0b21hdGljYWxseQpz
ZXRzIHVwIHRoZSBwcm9qZWN0IHN0cnVjdHVyZSBjb250YWluaW5nIGFsbCBzY3JpcHRzCnJl
cXVpcmVkIGZvciBwcm9jZXNzaW5nIGFuZCByZW5kZXJpbmcgTWFya2Rvd24uCgpGb3IgZXhh
bXBsZSwgZG93bmxvYWQgYG1hcmt5YCBmcm9tIGdpdGh1Yi4KYGBgYmFzaApnaXQgY2xvbmUg
aHR0cHM6Ly9sZWhtYW5uNy5naXRodWIuY29tL21hcmt5LmdpdApjZCBtYXJreQpgYGAKCkFm
dGVyIGRvd25sb2FkLCB0aGUgYG1hcmt5YCBlbnZpcm9ubWVudCBpcyBpbml0aWFsaXplZCB1
c2luZyBgbWFya3lgLgpgYGBiYXNoCi4vbWFya3kucHkgLS1pbml0CiMgbWtkaXIgYnVpbGQv
CiMgbWtkaXIgZGF0YQojIG1rZGlyIG1kLwojIFdSSVRFIE1ha2VmaWxlCiMgV1JJVEUgcGFu
ZG9jLXJ1bgojIFdSSVRFIG1kL21hcmt5Lm1kCiMgV1JJVEUgLmdpdGlnbm9yZQojIFVTQUdF
Cm1ha2UgaGVscApgYGAKCiMjIGBtYXJreWAgRW52aXJvbm1lbnQKCkR1cmluZyBpbml0aWFs
aXphdGlvbiwgYG1hcmt5YCBjcmVhdGVzIGRpcmVjdG9yaWVzIGFuZCBmaWxlcy4KQWZ0ZXIg
aW5pdGlhbGl6YXRpb24sIHRoZSBmb2xsb3dpbmcgc3RydWN0dXJlIGlzIGF1dG8tZ2VuZXJh
dGVkCmluIHRoZSBwcm9qZWN0IGRpcmVjdG9yeS4gYG1hcmt5YCBzaG93cyB0aGUgcHJvamVj
dCBzdHJ1Y3R1cmUKd2hlbiBpbnZva2luZyBgbWFrZSB0cmVlYC4KYGBgYmFzaAo8PwpfX18o
dGV4dF9wcm9jKCJtYWtlIHRyZWUiKSkKPz4KYGBgCgpUaGUgc2NyaXB0IGBwYW5kb2MtcnVu
YCBjYW4gYmUgYWRqdXN0ZWQgaW4gY2FzZSBzcGVjaWZpYwpgcGFuZG9jYCBvcHRpb25zIGFy
ZSByZXF1aXJlZCBmb3IgcmVuZGVyaW5nIHRoZSBgaHRtbGAgYW5kIGBwZGZgIGRvY3VtZW50
cy4KCiMjIERvY3VtZW50IFJlbmRlcmluZwoKQnkgaW52b2tpbmcgYG1ha2UgYWxsYCBhbGwg
ZmlsZXMgYG1kLyoubWRgIGFyZSB0cmFuc2Zvcm1lZAppbnRvIGNvcnJlc3BvbmRpbmcgYGh0
bWwvKi5odG1sYCBhbmQgYHBkZi8qLnBkZmAgZmlsZXMuIEJ5Cmludm9raW5nIGBtYWtlIGh0
dHBkYCBhIHB5dGhvbiB3ZWIgc2VydmVyIGlzIHN0YXJ0ZWQgaW4gYGh0bWwvYC4KCkFsbCB1
c2VyLWdlbmVyYXRlZCBNYXJrZG93biBjb250ZW50IGdvZXMgaW50byBgbWQvKmAgdXNlci1n
ZW5lcmF0ZWQKZGF0YSBmaWxlcyBnbyBpbnRvIGBkYXRhLypgLgoKKipBVFRFTlRJT046Kiog
VGhlIGZpbGVzIGluIHRoZSBkaXJlY3RvcmllcyBgYnVpbGQvKmAgYXJlCioqYXV0by1nZW5l
cmF0ZWQqKi4gQWxsIHVzZXIgZmlsZXMgaGF2ZSB0byBiZSBwbGFjZWQgaW5zaWRlIHRoZQpk
aXJlY3RvcnkgYG1kLypgLiBJbnZva2luZyBgbWFrZSBjbGVhbmAgd2lsbCAqKmRlbGV0ZSBh
bGwgZmlsZXMqKgppbiBgaHRtbC9gLCBgYnVpbGQvYCBhbmQgYHBkZi9gLgoKIyMgSW50ZWdy
YXRlZCBEb2N1bWVudGF0aW9uCgpgbWFya3lgIGhhcyBhbiBpbnRlZ3JhdGVkIGVudmlyb25t
ZW50LiBVc2luZyBgbWFrZSBoZWxwYCBkaXNwbGF5cwphIHNob3J0IGluZm8gYWJvdXQgdGhl
IGBtYXJreWAgZGVwZW5kZW5jaWVzLCBtYWtlIHRhcmdldHMgYW5kCmV4YW1wbGVzLgpgYGBi
YXNoCjw/Cl9fXyh0ZXh0X3Byb2MoIm1ha2UgaGVscCIpKQo/PgpgYGAKCiMgYG1hcmt5YCBG
ZWF0dXJlcwoKUGxhY2UgYSBuZXcgZmlsZSBpbiBgbWQvZmlsZS5tZGAgYW5kIHJ1biB0aGUg
Zm9sbG93aW5nIGNvbW1hbmRzLgpgYGBiYXNoCnRvdWNoIG1kL2ZpbGUubWQKYGBgCgpgbWFy
a3lgIGRpc2NvdmVycyB0aGUgbmV3IGRvY3VtZW50IHdoZW4gaW52b2tpbmcgYG1ha2Ugc2Nh
bmAuCmBgYGJhc2gKbWFrZSBzY2FuCiMgV1JJVEUgYnVpbGQvZmlsZS5tYWtlCmBgYAoKYG1h
cmt5YCByZW5kZXJzIGBodG1sYCBhbmQgYHBkZmAgdXNpbmcgbWFrZSB0YXJnZXRzLgpgYGBi
YXNoCm1ha2UgaHRtbC9maWxlCm1ha2UgcGRmL2ZpbGUKYGBgCgojIyBNZXRhIERhdGEgaW4g
RnJvbnQgTWF0dGVyCgpJZiBkb2N1bWVudCBzdGFydHMgd2l0aCBgLS0tYCwgeWFtbCBpcyB1
c2VkIHRvIHBhcnNlCnRoZSBmcm9udCBtYXR0ZXIgYmxvY2sgZGVsaW1pdGVkIGJ5IGAtLS1g
LgpBbGwgbWV0YSBkYXRhIGtleXMgd2lsbCBiZSBleHBvc2VkIGludG8gdGhlIHB5dGhvbiBz
Y29wZSBhcyBhIGxvY2FsCnZhcmlhYmxlLCB1bmxlc3MgdGhlIHZhcmlhYmxlIGFscmVhZHkg
ZXhpc3RzLgoKYGBgbWQKLS0tCnRpdGxlOiAiTXkgRG9jdW1ldCIKYXV0aG9yOiAuLi4KZGF0
ZTogMjAyMi0wMS0wMQotLS0KVGhlIHRpdGxlIG9mIHRoaXMgZG9jdW1lbnQgaXMge1x7dGl0
bGV9XH0uCmBgYAoKIyMgRW1iZWRkaW5nIFB5dGhvbiBDb2RlCgpQeXRob24gY29kZSBibG9j
a3MgYXJlIGVtYmVkZGVkIGludG8gTWFya2Rvd24gdXNpbmcgYDxcPy4uLj9cPmAgYW5kIGB7
XHsuLi59XH1gLgpBbGwgY29kZSBibG9ja3Mgc3BhbiBvbmUgbGFyZ2Ugc2NvcGUgc2hhcmlu
ZyBmdW5jdGlvbnMgYW5kIGxvY2FsCnZhcmlhYmxlcy4gTWV0YSBkYXRhIGlzIGltcG9ydGVk
IGZyb20gTWFya2Rvd24gZnJvbnQgbWF0dGVyIGFzIGxvY2FsCnZhcmlhYmxlcyBpbiB0aGUg
cHl0aG9uIHNjb3BlLiBUaGUgYGltcG9ydGAgc3RhdGVtZW50IGNhbiBiZSB1c2VkIGluCnB5
dGhvbiBjb2RlIGluIG9yZGVyIHRvIGFjY2VzcyBpbnN0YWxsZWQgcHl0aG9uIHBhY2thZ2Vz
IGFzIHVzdWFsLgoKIyMjIFZpc2libGUgQ29kZQoKVXNpbmcgYDxcPyEuLi4/XD5gIGNvZGUg
aXMgZXhlY3V0ZWQgYW5kIGFsc28gc2hvd24gaW4gTWFya2Rvd24uCgojIyMjIEV4YW1wbGUg
ey19CmBgYHB5dGhvbgo8XD8hCnggPSA0MiAjIHZpc2libGUgY29kZQpwcmludCgiSGVsbG8g
Y29uc29sZSEiKQo/XD4KYGBgCgojIyMjIFJ1biBhbmQgT3V0cHV0IHstfQpgYGBweXRob248
PyEKeCA9IDQyICMgdmlzaWJsZSBjb2RlCj8+CmBgYAoKKipBVFRFTlRJT046KiogVXNpbmcg
dGhlIGBwcmludCgpYCBmdW5jdGlvbiB0aGUgdGV4dCB3aWxsIGJlIHByaW50ZWQKdG8gdGhl
IGNvbnNvbGUgYW5kICoqbm90KiogaW5zaWRlIHRoZSByZXN1bHRpbmcgTWFya2Rvd24gdGV4
dC4KCiMjIyBIaWRkZW4gQ29kZQoKVXNpbmcgYDxcPy4uLj9cPmAgY29kZSBpcyBleGVjdXRl
ZCBidXQgbm90IHNob3duIGluIE1hcmtkb3duLgoKIyMjIyBFeGFtcGxlIHstfQpgYGBweXRo
b24KPFw/CnggPSA0MSAjIGhpZGRlbiBjb2RlCl9fXyhmIk91dHB1dCB0byBNYXJrZG93bi4g
eCA9IHt4fSEiKQo/XD4KYGBgCiMjIyMgUnVuIGFuZCBPdXRwdXQgey19CmBgYHB5dGhvbgo8
Pwp4ID0gNDEgIyBoaWRkZW4gY29kZQpfX18oZiJPdXRwdXQgdG8gTWFya2Rvd24uIHggPSB7
eH0hIikKPz4KYGBgCgoqKkFUVEVOVElPTjoqKiBVc2luZyB0aGUgYF9fXygpYCBmdW5jdGlv
biB0aGUgdGV4dCB3aWxsIGJlIHByaW50ZWQKaW5zaWRlIHRoZSByZXN1bHRpbmcgTWFya2Rv
d24gdGV4dCAqKmFuZCBub3QqKiBvbiB0aGUgY29uc29sZS4KCiMjIFRoZSBgX19fKClgIEZ1
bmN0aW9uCgpVc2luZyB0aGUgYHByaW50KClgIHN0YXRlbWVudCB0aGUgdGV4dCB3aWxsIGJl
IHByaW50ZWQgdG8gdGhlIGNvbnNvbGUuCldoZW4gdXNpbmcgdGhlIGBfX18oKWAgc3RhdGVt
ZW50IG5ldyBNYXJrZG93biB0ZXh0IGlzCmluc2VydGVkIGR5bmFtaWNhbGx5IGludG8gdGhl
IGRvY3VtZW50IGR1cmluZyBwcmVwcm9jZXNzaW5nLgoKIyMjIyBFeGFtcGxlOiBMaW5lIEJy
ZWFrIHstfQpgYGBweXRob24KPFw/CnggPSA0MCAjIGhpZGRlbiBjb2RlCl9fXygiT3V0cHV0
IGluIiwgX19fKQpfX18oInNpbmdsZSBsaW5lISAiLCBfX18pCl9fXyhmInggPSB7eH0iKQo/
XD4KYGBgCiMjIyMgUnVuIGFuZCBPdXRwdXQgey19CmBgYGJhc2gKPD8KeCA9IDQwICMgaGlk
ZGVuIGNvZGUKX19fKCJPdXRwdXQgaW4gIiwgX19fKQpfX18oInNpbmdsZSBsaW5lISAiLCBf
X18pCl9fXyhmInggPSB7eH0iKQo/PgpgYGAKCiMjIyMgRXhhbXBsZTogU2hpZnQsIENyb3As
IFJldHVybiB7LX0KYGBgcHl0aG9uCjxcPwpyZXN1bHQgPSBfX18oIiIiCiAgICogdGV4dCBp
cyBjcm9wcGVkIGFuZCBzaGlmdGVkCiAgICAgICAgICogc2hpZnQgYW5kIGNyb3AKICAgICAg
ICAgICAgKiBjYW4gYmUgY29tYmluZWQKICAgICAgICAgICogcmV0dXJuaW5nIHRoZSByZXN1
bHQKIiIiLCBzaGlmdD0iIyMjIyMjIyMiLCBjcm9wPVRydWUsIHJldD1UcnVlKQpfX18ocmVz
dWx0KQo/XD4KYGBgCiMjIyMgUnVuIGFuZCBPdXRwdXQgey19CmBgYGJhc2gKPD8KcmVzdWx0
ID0gX19fKCIiIgogICAqIHRleHQgaXMgY3JvcHBlZCBhbmQgc2hpZnRlZAogICAgICAgICAq
IHNoaWZ0IGFuZCBjcm9wCiAgICAgICAgICAgICogY2FuIGJlIGNvbWJpbmVkCiAgICAgICAg
ICAqIHJldHVybmluZyB0aGUgcmVzdWx0CiIiIiwgc2hpZnQ9IiMjIyMjIyMjIiwgY3JvcD1U
cnVlLCByZXQ9VHJ1ZSkKX19fKHJlc3VsdCkKPz4KYGBgCgojIyBBbGdvcml0aG1pYyBUYWJs
ZSBFeGFtcGxlCgpAdGJsOmFsZ3QgaXMgZ2VuZXJhdGVkIHVzaW5nIHRoZSBmb2xsb3dpbmcg
cHl0aG9uIGNsb2RlIGJsb2NrLgoKYGBgcHl0aG9uPD8hCm4gPSA1CnRhYmxlID0gIiIKZGVj
ID0gWyIqJXMqIiwgIioqJXMqKiIsICJ+fiVzfn4iLCAiYCVzYCIsCiAgICAgICByIiRcdGlt
ZXNeJXMkIiwgIiRcaW5mdHlfJXMkIl0KdGFibGUgKz0gInwiLmpvaW4oIlgiKm4pICsgIlxu
IiArICJ8Ii5qb2luKCItIipuKSArICJcbiIKZm9yIGkgaW4gcmFuZ2Uobik6CglmaWxsID0g
W2NocihvcmQoIkEiKSsoMippKzMqayklMjYpIGZvciBrIGluIHJhbmdlKGkrMSldCglmaWxs
ID0gW2RlY1sobCtpKSVsZW4oZGVjKV0layBmb3IgbCwgayBpbiBlbnVtZXJhdGUoZmlsbCld
Cgl0ZXh0ID0gbGlzdCgiMCIpKm4KCXRleHRbKG4+PjEpLShpPj4xKToobj4+MSkrKGk+PjEp
XSA9IGZpbGwKCXRhYmxlICs9ICJ8Ii5qb2luKHRleHQpICsgIlxuIgo/PgpgYGAKCnt7dGFi
bGV9fQoKVGFibGU6IFRhYmxlIGlzIGdlbmVyYXRlZCB1c2luZyBjb2RlIGFuZCB0aGUgYF9f
XygpYCBzdGF0ZW1lbnQuIHsjdGJsOmFsZ3R9CgojIyBJbmxpbmUgRm9ybWF0dGVkIE91dHB1
dAoKVGhlIGB7XHsuLi59XH1gIHN0YXRlbWVudCB1c2VzIHNudGF4IHNpbWlsYXIgdG8gcHl0
aG9uIGBmYC1zdHJpbmdzIGZvcgpmb3JtYXR0ZWQgb3V0cHV0IG9mIHZhcmlhYmxlcyBhbmQg
cmVzdWx0cyBvZiBleHByZXNzaW9ucyBpbnRvIE1hcmtkb3duCnRleHQuIFRoZSBgbWFya3lg
IG9wZXJhdG9yIGB7XHs8ZXhwcmVzc2lvbj5bOjxmb3JtYXQ+XX1cfWAgdXNlcyB0aGUKc3lu
dGF4IG9mIFtgZmAtc3RyaW5nc10oaHR0cHM6Ly9kb2NzLnB5dGhvbi5vcmcvMy9yZWZlcmVu
Y2UvbGV4aWNhbF9hbmFseXNpcy5odG1sI2Ytc3RyaW5ncykuCgojIyMjIEV4YW1wbGUgMSB7
LX0KYGBgYmFzaApgeGAgaXMge1x7eH1cfSBhbmQge1x7IiwiLmpvaW4oW3N0cihpKSBmb3Ig
aSBpbiByYW5nZSh4LTEwLHgpXSl9XH0uCmBgYAojIyMjIE91dHB1dCB7LX0KPiBgeGAgaXMg
e3t4fX0gYW5kIHt7IiwiLmpvaW4oW3N0cihpKSBmb3IgaSBpbiByYW5nZSh4LTEwLHgpXSl9
fS4KCiMjIyMgRXhhbXBsZSAyIHstfQpgYGBweXRob248PyEKeCA9IGludCgxKQp5ID0gZmxv
YXQoMi4zKQp6ID0gMAphID0gWzEsIDIsIDNdCmIgPSAoNCwgNSkKPz4KYGBgCmBgYG1hcmtk
b3duClRoaXMgaXMgYSBwYXJhZ3JhcGggYW5kIHggaXMge1x7eDowM2R9XH0gYW5kIHkgaXMg
e1x7eTouMmZ9XH0uCk90aGVyIGNvbnRlbnQgaXM6IGEgPSB7XHthfVx9LCBiID0ge1x7Yn1c
fS4KYGBgCiMjIyMgT3V0cHV0IHstfQo+IFRoaXMgaXMgYSBwYXJhZ3JhcGggYW5kIHggaXMg
e3t4OjAzZH19IGFuZCB5IGlzIHt7eTouMmZ9fS4KPiBPdGhlciBjb250ZW50IGlzOiBhID0g
e3thfX0sIGIgPSB7e2J9fS4KCiMjIEZvcm1hdCBMaW5rIEV4dGVuc2lvbgoKV2hlbiB3cml0
aW5nIG11bHRpcGxlIGRvY3VtZW50cywgb2Z0ZW4gZG9jdW1lbnRzIGFyZSByZWZlcmVuY2Vk
CmJldHdlZW4gZWFjaCBvdGhlciB1c2luZyBsaW5rcy4gSW4gb3JkZXIgdG8gcmVmZXIgdG8g
ZXh0ZXJuYWwKYGh0bWxgIGFuZCBgcGRmYCBkb2N1bWVudHMgdGhlIE1hcmtkb3duIGxpbmsg
c3RhdGVtZW50IGlzIHVzZWQuCmBgYG1kCltMaW5rIENhcHRpb25dKHBhdGgvdG8vZmlsZS5o
dG1sKQpbTGluayBDYXB0aW9uXShwYXRoL3RvL2ZpbGUucGRmKQpgYGAKT25lIGxpbmsgc3Rh
dGVtZW50IGNhbm5vdCBiZSB1c2VkIGZvciByZW5kZXJpbmcgYGh0bWxgIGFuZCBgcGRmYAp3
aXRoIGNvbnNpc3RlbnQgcGF0aHMuIFVzaW5nIHRoZSBgbWFya3lgIGZvcm1hdCBsaW5rCiBg
Llw/Pz9gIGZpbGUgZXh0ZW5zaW9uIHJlc3VsdHMgaW4gY29uc2lzdGVudCBsaW5rcyBmb3Ig
YGh0bWxgIGFuZApgcGRmYCBkb2N1bWVudHMuCgojIyMjIEV4YW1wbGUgey19CmBgYG1kCltM
aW5rIHRvIHRoaXMgRG9jdW1lbnRdKG1hcmt5Llw/Pz8pCmBgYAojIyMjIE91dHB1dCB7LX0K
PiBbTGluayB0byB0aGlzIERvY3VtZW50XShtYXJreS4/Pz8pCgojIyBGb3JtYXQgQ29kZXMK
Ck9mdGVuIHdoZW4gd3JpdGluZyBtYXJrZG93biBmb3IgYGh0bWxgIGFuZCBgcGRmYCBkb2N1
bWVudHMsIHRoZQpvdXRwdXQgbmVlZHMgdG8gYmUgdHdlYWtlZCBhY2NvcmRpbmdseS4KYG1h
cmt5YCBzdXBwb3J0cyBmb3JtYXQgc3BlY2lmaWMgdHdlYWtpbmcgYnkgaW5qZWN0aW5nCnJh
dyBgaHRtbGAgb3IgYHRleGAgY29kZSBpbnRvIE1hcmtkb3duIHVzaW5nIGZvcm1hdCBjb2Rl
cy4KCkluIG9yZGVyIHRvIGluamVjdCBmb3JtYXQgc3BlY2lmaWMgY29kZSB0aGUgYGZtdGNv
ZGVgIGNsYXNzIGlzIHVzZWQuClRoZSBgZm10Y29kZWAgY2xhc3MgbWFuYWdlcyBpbmplY3Rp
b24gb2YgYGh0bWxgIGFuZCBgdGV4YCBjb2RlCmRlcGVuZGluZyBvbiB0aGUgb3V0cHV0IGZv
cm1hdC4KCioqQVRURU5USU9OOioqIGB0ZXhgIHBhY2thZ2VzIGhhdmUgdG8gYmUgaW5jbHVk
ZWQgZm9yIGBwZGZgIGFzIHdlbGwgYXMKSmF2YVNjcmlwdCBhbmQgc3R5bGUgc2hlZXRzIGZv
ciBgaHRtbGAgdXNpbmcgdGhlIG1ldGEgZGF0YSBmaWVsZHMKYGhlYWRlci1pbmNsdWRlcy0t
cGRmYCBhbmQgYGhlYWRlci1pbmNsdWRlcy0taHRtbGAgcmVzcGVjdGl2ZWx5LgoKIyMjIyBF
eGFtcGxlOiBgZm10Y29kZWAgey19CmBgYHB5dGhvbjw/IQpGID0gZm10Y29kZShodG1sPSJI
PHN1cD5UPC9zdXA+PHN1Yj5NPC9zdWI+TCIsIHBkZj1yIlxMYVRlWCIpCj8+CmBgYApgYGBt
YXJrZG93bgpJbnZvY2F0aW9uIG9mIGZvcm1hdCBjb2RlIHJlc3VsdHMgaW46IHtce0YoKX1c
fS4KYGBgCiMjIyMgT3V0cHV0IHstfQo+IEludm9jYXRpb24gb2YgZm9ybWF0IGNvZGUgcmVz
dWx0cyBpbjoge3tGKCl9fS4KCiMjIyMgRXhhbXBsZTogQ29sb3Igey19CmBgYHB5dGhvbjw/
IQpDID0gbGFtYmRhIGNvbG9yOiBmbXRjb2RlKAoJaHRtbD0iPHNwYW4gc3R5bGU9J2NvbG9y
OiVzOyc+ezB9PC9zcGFuPiIgJSBjb2xvciwKCXBkZj1yIlx0ZXh0Y29sb3J7eyVzfX17e3sw
fX19IiAlIGNvbG9yCikKQiA9IEMoImJsdWUiKQpSID0gQygicmVkIikKPz4KYGBgCmBgYG1h
cmtkb3duClRleHQgd2l0aCB7XHtCKCJibHVlIil9XH0gYW5kIHtce1IoIlJFRCIpfVx9Lgpg
YGAKIyMjIyBPdXRwdXQgey19Cj4gVGV4dCB3aXRoIHt7QigiYmx1ZSIpfX0gYW5kIHt7Uigi
UkVEIil9fS4KCgojIyMjIEV4YW1wbGU6IENsYXNzZXMgey19CmBgYHB5dGhvbjw/IQpjbGFz
cyBjb2xvcjoKCWRlZiBfX2luaXRfXyhzZWxmLCBjb2xvcik6CgkJc2VsZi5jb2xvciA9IGNv
bG9yCglkZWYgdXBwZXIoc2VsZiwgeCk6CgkJcmV0dXJuIHNlbGYudGV4dCh4LnVwcGVyKCkp
CglkZWYgbG93ZXIoc2VsZiwgeCk6CgkJcmV0dXJuIHNlbGYudGV4dCh4Lmxvd2VyKCkpCgpj
bGFzcyBodG1sKGNvbG9yKToKCWRlZiB0ZXh0KHNlbGYsIHgpOgoJCXJldHVybiBmIjxzcGFu
IHN0eWxlPSdjb2xvcjp7c2VsZi5jb2xvcn07Jz57eH08L3NwYW4+IgoKY2xhc3MgcGRmKGNv
bG9yKToKCWRlZiB0ZXh0KHNlbGYsIHgpOgoJCXJldHVybiByZiJcdGV4dGNvbG9ye3t7c2Vs
Zi5jb2xvcn19fXt7e3h9fX0iCgpDQyA9IGxhbWJkYSB4OiBmbXRjb2RlKGh0bWw9aHRtbCh4
KSwgcGRmPXBkZih4KSkKQkIgPSBDQygiYmx1ZSIpClJSID0gQ0MoInJlZCIpCj8+CmBgYApg
YGBtYXJrZG93bgpUZXh0IHdpdGgge1x7QkIudXBwZXIoImJsdWUiKX1cfSBhbmQge1x7UlIu
bG93ZXIoIlJFRCIpfVx9LgpgYGAKIyMjIyBPdXRwdXQgey19Cj4gVGV4dCB3aXRoIHt7QkIu
dXBwZXIoImJsdWUiKX19IGFuZCB7e1JSLmxvd2VyKCJSRUQiKX19LgoKIyBNZXRhIERhdGEg
aW4gRnJvbnQgTWF0dGVyCgpNZXRhIGRhdGEgaXMgYW5ub3RhdGVkIGluIHRoZSBmcm9udCBt
YXR0ZXIgb2YgYSAJTWFya2Rvd24gdGV4dCBkb2N1bWVudC4KVGhlIGZyb250IG1hdHRlciBt
dXN0IHN0YXJ0IGluIHRoZSBmaXJzdCBsaW5lIHdpdGggYC0tLWAgYW5kIHByZWNlZGVzIGFs
bApvdGhlciB0ZXh0IGJlaW5nIGZlbmNlZCBieSBgLS0tYC4gVGhlIG1ldGEgZGF0YSBpcyBp
biBgeWFtbGAgZm9ybWF0LgpUaGUgYHlhbWxgIGJsb2NrIGlzIHBhcnNlZCB1c2luZyBgcHl0
aG9uLXB5eWFtbGAuIEFsbCBtZXRhCmRhdGEgaXMgaW1wb3J0ZWQgaW50byB0aGUgcHJlcHJv
Y2Vzc2VkIGRvY3VtZW50LgoKIyMgUGFuZG9jIEZyb250IE1hdHRlcgoKIyMjIyBFeGFtcGxl
IHstfQpgYGB5YW1sCi0tLQp0aXRsZToKZGF0ZToKYXV0aG9yOgpsaW5rLWNpdGF0aW9uczoK
YmlibGlvZ3JhcGh5OgpoZWFkZXItaW5jbHVkZXM6Cnhub3MtY2xldmVyZWY6Cnhub3MtY2Fw
aXRhbGlzZToKZm9udHNpemU6Ci0tLQpgYGAKVGhlIG1ldGEgZGF0YSBmaWVsZHMKW2B0aXRs
ZWAsIGBkYXRlYCwgYGF1dGhvcmBdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNt
ZXRhZGF0YS12YXJpYWJsZXMpLApbYGxpbmstY2l0YXRpb25zYF0oaHR0cHM6Ly9wYW5kb2Mu
b3JnL01BTlVBTC5odG1sI290aGVyLXJlbGV2YW50LW1ldGFkYXRhLWZpZWxkcyksCltgYmli
bGlvZ3JhcGh5YF0oaHR0cHM6Ly9wYW5kb2Mub3JnL01BTlVBTC5odG1sI2NpdGF0aW9uLXJl
bmRlcmluZykgYW5kCltgaGVhZGVyLWluY2x1ZGVzYF0oaHR0cHM6Ly9wYW5kb2Mub3JnL01B
TlVBTC5odG1sI3ZhcmlhYmxlcy1zZXQtYXV0b21hdGljYWxseSkKYXJlIHByb2Nlc3NlZCBi
eSBgcGFuZG9jYCBkdXJpbmcgZG9jdW1lbnQgcmVuZGVyaW5nLiBgZm9udHNpemVgIGFkanVz
dHMgdGhlCmZvbnQgc2l6ZSBpbiBbYGh0bWxgXShodHRwczovL3BhbmRvYy5vcmcvTUFOVUFM
Lmh0bWwjdmFyaWFibGVzLWZvci1odG1sKQphbmQgW2BwZGZgXShodHRwczovL3BhbmRvYy5v
cmcvTUFOVUFMLmh0bWwjdmFyaWFibGVzLWZvci1sYXRleCkgZG9jdW1lbnRzLgpUaGUgYHhu
b3MtY2xldmVyZWZgIGFuZCBgeG5vcy1jYXBpdGFsaXNlYApmaWVsZHMgYXJlIHVzZWQgYnkg
dGhlIFtgcGFuZG9jLXhub3NgXShodHRwczovL2dpdGh1Yi5jb20vdG9tZHVjay9wYW5kb2Mt
eG5vcykKZXh0ZW5zaW9ucyBmb3IgcmVmZXJlbmNpbmcKW2ZpZ3VyZXNdKGh0dHBzOi8vZ2l0
aHViLmNvbS90b21kdWNrL3BhbmRvYy1maWdub3MjY3VzdG9taXphdGlvbiksClt0YWJsZXNd
KGh0dHBzOi8vZ2l0aHViLmNvbS90b21kdWNrL3BhbmRvYy10YWJsZW5vcyNjdXN0b21pemF0
aW9uKSwKW3NlY3Rpb25zXShodHRwczovL2dpdGh1Yi5jb20vdG9tZHVjay9wYW5kb2Mtc2Vj
bm9zI2N1c3RvbWl6YXRpb24pIGFuZApbZXF1YXRpb25zXShodHRwczovL2dpdGh1Yi5jb20v
dG9tZHVjay9wYW5kb2MtZXFub3MjY3VzdG9taXphdGlvbikuCgojIyBgbWFya3lgIEZvcm1h
dCBGaWVsZHMKCioqRXhhbXBsZSoqCmBgYHlhbWwKLS0tCmhlYWRlci1pbmNsdWRlcy0tcGRm
OiA+CiAgXGh5cGVyc2V0dXB7CiAgY29sb3JsaW5rcz1mYWxzZSwKICBhbGxib3JkZXJjb2xv
cnM9ezAgMCAwfSwKICBwZGZib3JkZXJzdHlsZT17L1MvVS9XIDF9XH0KaGVhZGVyLWluY2x1
ZGVzLS1odG1sOiA+CiAgPHN0eWxlPiogeyBib3gtc2l6aW5nOiBib3JkZXItYm94OyB9PC9z
dHlsZT4KLS0tCmBgYAoKVGhlIHBhbmRvYyBgaGVhZGVyLWluY2x1ZGVzYCBmaWVsZCBpcyB1
c2VkIGZvciBgcGRmYCBhbmQgYGh0bWxgIGRvY3VtZW50cywKdGhlcmVmb3JlIGl0IG11c3Qg
Y29udGFpbiBjb3JyZXNwb25kaW5nIHRleCBhbmQgYGh0bWxgIGNvZGUuCgpUaGUgZmllbGQg
YGhlYWRlci1pbmNsdWRlc2AgZW5kaW5nIHdpdGggYC0tcGRmYCBvciBgLS1odG1sYApzcGVj
aWZpZXMgY29ycmVzcG9uZGluZyBvcHRpb25zIGZvciB0aGUgZ2VuZXJhdGlvbiBvZiBgcGRm
YCBhbmQgYGh0bWxgCmRvY3VtZW50cy4gRHVyaW5nIG1ha2UsIGBtYXJreWAgc2NhbnMgYWxs
IG1ldGEgZGF0YSBmaWVsZHMsIGFuZApmaWVsZHMgd2hpY2ggZW5kIHdpdGggYC0tcGRmYCBh
bmQgYC0taHRtbGAgYXJlIHNlbGVjdGVkIGFuZCBmb3J3YXJkZWQKdG8gYHBhbmRvY2AgYmFz
ZWQgb24gdGhlIGZvcm1hdCB0byBiZSByZW5kZXJlZC4KCiMgU2NpZW50aWZpYyBXcml0aW5n
IGluIE1hcmtkb3duIHsjc2VjOnBhbm1kfQoKW01hcmtkb3duXShodHRwczovL3BhbmRvYy5v
cmcvTUFOVUFMLmh0bWwjcGFuZG9jcy1tYXJrZG93bikgaXMgYSBtYXJrdXAKbGFuZ3VhZ2Ug
Zm9yIHRlY2huaWNhbCB3cml0aW5nLCB3aXRoIGVtcGhhc2lzIG9uIHJlYWRhYmlsaXR5LiBN
YXJrZG93bgpjYW4gYmUgcmVuZGVyZWQgaW4gbWFueSBmb3JtYXRzIGluY2x1ZGluZyBgaHRt
bGAgYW5kIGBwZGZgIGJ5IHVzaW5nCltgcGFuZG9jYF0oaHR0cHM6Ly9wYW5kb2Mub3JnLykg
Zm9yIGV4YW1wbGUuCgpVc2luZyB2YXJpb3VzIE1hcmtkb3duIGV4dGVuc2lvbnMgb2YgYHBh
bmRvY2AgYSBzdWZmaWNpZW50IHN0cnVjdHVyZSBmb3IKd3JpdGluZyBzY2llbnRpZmljIGRv
Y3VtZW50cyBpcyByZWZsZWN0ZWQgdXNpbmcgTWFya2Rvd24gc3ludGF4LgpgbWFya3lgIGJ5
IGRlZmF1bHQgdXNlcyB0aGUgZm9sbG93aW5nIGBwYW5kb2NgIE1hcmtkb3duIGV4dGVuc2lv
bnMuCiogcGFyc2luZyBleHRlbnNpb25zCgkqIFthbGxfc3ltYm9sc19lc2NhcGFibGVdKGh0
dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNleHRlbnNpb24tYWxsX3N5bWJvbHNfZXNj
YXBhYmxlKQoJKiBbaW50cmF3b3JkX3VuZGVyc2NvcmVzXShodHRwczovL3BhbmRvYy5vcmcv
TUFOVUFMLmh0bWwjZXh0ZW5zaW9uLWludHJhd29yZF91bmRlcnNjb3JlcykKCSogW2VzY2Fw
ZWRfbGluZV9icmVha3NdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNleHRlbnNp
b24tZXNjYXBlZF9saW5lX2JyZWFrcykKCSogW3NwYWNlX2luX2F0eF9oZWFkZXJdKGh0dHBz
Oi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNleHRlbnNpb24tc3BhY2VfaW5fYXR4X2hlYWRl
cikKCSogW2xpc3RzX3dpdGhvdXRfcHJlY2VkaW5nX2JsYW5rbGluZV0oaHR0cHM6Ly9wYW5k
b2Mub3JnL01BTlVBTC5odG1sI2V4dGVuc2lvbi1saXN0c193aXRob3V0X3ByZWNlZGluZ19i
bGFua2xpbmUpCiogc3R5bGluZyBleHRlbnNpb25zCgkqIFtpbmxpbmVfY29kZV9hdHRyaWJ1
dGVzXShodHRwczovL3BhbmRvYy5vcmcvTUFOVUFMLmh0bWwjZXh0ZW5zaW9uLWlubGluZV9j
b2RlX2F0dHJpYnV0ZXMpCgkqIFtzdHJpa2VvdXRdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5V
QUwuaHRtbCNleHRlbnNpb24tc3RyaWtlb3V0KQoqIHN0cnVjdHVyaW5nIGV4dGVuc2lvbnMK
CSogW3lhbWxfbWV0YWRhdGFfYmxvY2tdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRt
bCNleHRlbnNpb24teWFtbF9tZXRhZGF0YV9ibG9jaykKCSogW3BpcGVfdGFibGVzXShodHRw
czovL3BhbmRvYy5vcmcvTUFOVUFMLmh0bWwjZXh0ZW5zaW9uLXBpcGVfdGFibGVzKQoJKiBb
bGluZV9ibG9ja3NdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNleHRlbnNpb24t
bGluZV9ibG9ja3MpCgkqIFtpbXBsaWNpdF9maWd1cmVzXShodHRwczovL3BhbmRvYy5vcmcv
TUFOVUFMLmh0bWwjZXh0ZW5zaW9uLWltcGxpY2l0X2ZpZ3VyZXMpCgkqIFthYmJyZXZpYXRp
b25zXShodHRwczovL3BhbmRvYy5vcmcvTUFOVUFMLmh0bWwjZXh0ZW5zaW9uLWFiYnJldmlh
dGlvbnMpCgkqIFtpbmxpbmVfbm90ZXNdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRt
bCNleHRlbnNpb24taW5saW5lX25vdGVzKQoqIGNvZGUgaW5qZWN0aW9uCgkqIFtyYXdfaHRt
bF0oaHR0cHM6Ly9wYW5kb2Mub3JnL01BTlVBTC5odG1sI2V4dGVuc2lvbi1yYXdfaHRtbCkK
CSogW3Jhd190ZXhdKGh0dHBzOi8vcGFuZG9jLm9yZy9NQU5VQUwuaHRtbCNleHRlbnNpb24t
cmF3X3RleCkKCmBwYW5kb2NgIHN1cHBvcnRzCltlcXVhdGlvbnNdKGh0dHBzOi8vcGFuZG9j
Lm9yZy9NQU5VQUwuaHRtbCNleHRlbnNpb24tdGV4X21hdGhfZG9sbGFycykKcmVuZGVyZWQg
aW5saW5lIGFuZCBzaW5nbGUtbGluZSBpbiB0ZXgtc3R5bGUgdXNpbmcgYCQuLi4kYCBhbmQg
YCQkLi4uJCRgLApbYmlibGlvZ3JhcGh5XShodHRwczovL3BhbmRvYy5vcmcvTUFOVUFMLmh0
bWwjY2l0YXRpb25zKQp1c2luZyB0aGUgYC0tY2l0ZXByb2NgIG9wdGlvbiwKW3NlY3Rpb24g
bnVtYmVyaW5nXShodHRwczovL3BhbmRvYy5vcmcvTUFOVUFMLmh0bWwjZXh0ZW5zaW9uLWhl
YWRlcl9hdHRyaWJ1dGVzKQp1c2luZyB0aGUgYC0tbnVtYmVyLXNlY3Rpb25zYCBvcHRpb24g
YW5kClt0YWJsZSBvZiBjb250ZW50c10oaHR0cHM6Ly9wYW5kb2Mub3JnL01BTlVBTC5odG1s
I29wdGlvbi0tdG9jKQp1c2luZyB0aGUgYC0tdGFibGUtb2YtY29udGVudHNgIG9wdGlvbi4K
CmBwYW5kb2NgIHN1cHBvcnRzIFtgeG5vc2BdKGh0dHBzOi8vZ2l0aHViLmNvbS90b21kdWNr
L3BhbmRvYy14bm9zKSBmaWx0ZXJzCmZvciByZWZlcmVuY2luZyBkb2N1bWVudCBjb250ZW50
IGxpa2UKW2ZpZ3VyZXNdKGh0dHBzOi8vZ2l0aHViLmNvbS90b21kdWNrL3BhbmRvYy1maWdu
b3MjdXNhZ2UpLApbZXF1YXRpb25zXShodHRwczovL2dpdGh1Yi5jb20vdG9tZHVjay9wYW5k
b2MtZXFub3MjdXNhZ2UpLApbdGFibGVzXShodHRwczovL2dpdGh1Yi5jb20vdG9tZHVjay9w
YW5kb2MtdGFibGVub3MjdXNhZ2UpLApbc2VjdGlvbnNdKGh0dHBzOi8vZ2l0aHViLmNvbS90
b21kdWNrL3BhbmRvYy1zZWNub3MjdXNhZ2UpCmJ5IHVzaW5nIHRoZSBgLS1maWx0ZXIgcGFu
ZG9jLXhub3NgIG9wdGlvbi4KYHhub3NgIGludGVncmF0ZXMgY2xldmVyIHJlZmVyZW5jZXMs
IHdoaWNoIG1lYW5zICJGaWcuIiwgIlNlYy4iLCAiRXEuIgphbmQgIlRhYi4iIGFyZSBhZGRl
ZCBhdXRvbWF0aWNhbGx5IHRvIHRoZSBjb3JyZXNwb25kaW5nIGVsZW1lbnQuCklmIHRoZSBw
cmVmaXggaXMgdG8gYmUgb21pdHRlZCwgdGhlIHJlZmVyZW5jZSBpcyB3cml0dGVuIGFzCmBc
IUByZWY6bGFiZWxgLgoKIyMjIyBFeGFtcGxlIHstfQpgYGBtZAojIyBSZWZlcmVuY2VkIFNl
Y3Rpb24geyNzZWM6bGFiZWx9CgpUaGlzIGlzIGEgcmVmZXJlbmNlIHRvIEBzZWM6bGFiZWwu
CgohW1RoaXMgaXMgdGhlIGNhcHRpb25dKGRhdGE6aW1hZ2UvcG5nO2Jhc2U2NCxpVkJPUncw
S0dnb0FBQUFOUwpVaEVVZ0FBQUFVQUFBQUZDQVlBQUFDTmJ5YmxBQUFBSEVsRVFWUUkxMlA0
Ly84L3czOEdJQVhESUJLRTBESAp4Z2xqTkJBQU85VFhMMFk0T0h3QUFBQUJKUlU1RXJrSmdn
Zz09KXsjZmlnOmxhYmVsfQoKVGhpcyBpcyBhIHJlZmVyZW5jZSB0byBAZmlnOmxhYmVsLgoK
QSAgfEIgIHxDICB8RAotLS18LS0tfC0tLXwtLS0KMDAwfDExMXw0NDR8NTU1CjIyMnwzMzN8
NjY2fDc3NwoKVGFibGU6IFRoaXMgaXMgdGhlIGNhcHRpb24geyN0Ymw6bGFiZWx9CgpUaGlz
IGlzIGEgcmVmZXJlbmNlIHRvIEB0Ymw6bGFiZWwuCgokJFxtYm94e2V9XntcbWJveHtpfVxw
aX0rMT0wJCR7I2VxOmxhYmVsfQoKVGhpcyBpcyBhIHJlZmVyZW5jZSB0byBAZXE6bGFiZWwu
CgpUaGlzIGlzIGEgY2l0YXRpb24gW0BNdWxsZXIxOTkzXS4KYGBgCgpUaGUgZmlsZSBgbWFy
a3kuYmliYCBpcyBzcGVjaWZpZWQgaW4gdGhlIG1ldGEgZGF0YSBpbiB0aGUgZnJvbnQKbWF0
dGVyIG9mIHRoZSBNYXJrZG93biB0ZXh0LgoKIyMgUmVmZXJlbmNlZCBTZWN0aW9uIHsjc2Vj
OmxhYmVsfQoKVGhpcyBpcyBhIHJlZmVyZW5jZSB0byBAc2VjOmxhYmVsLgoKIVtUaGlzIGlz
IHRoZSBjYXB0aW9uXShkYXRhOmltYWdlL3BuZztiYXNlNjQsaVZCT1J3MEtHZ29BQUFBTlNV
aEVVZ0FBQUFVQUFBQUZDQVlBQUFDTmJ5YmxBQUFBSEVsRVFWUUkxMlA0Ly84L3czOEdJQVhE
SUJLRTBESHhnbGpOQkFBTzlUWEwwWTRPSHdBQUFBQkpSVTVFcmtKZ2dnPT0peyNmaWc6bGFi
ZWx9CgpUaGlzIGlzIGEgcmVmZXJlbmNlIHRvIEBmaWc6bGFiZWwuCgpBICB8QiAgfEMgIHxE
Ci0tLXwtLS18LS0tfC0tLQowMDB8MTExfDQ0NHw1NTUKMjIyfDMzM3w2NjZ8Nzc3CgpUYWJs
ZTogVGhpcyBpcyB0aGUgY2FwdGlvbi4geyN0Ymw6bGFiZWx9CgpUaGlzIGlzIGEgcmVmZXJl
bmNlIHRvIEB0Ymw6bGFiZWwuCgokJFxtYm94e2V9XntpXHBpfSsxPTAkJHsjZXE6bGFiZWx9
CgpUaGlzIGlzIGEgcmVmZXJlbmNlIHRvIEBlcTpsYWJlbC4KClRoaXMgaXMgYSBjaXRhdGlv
biBbQE11bGxlcjE5OTNdLgoKIyBSZWZlcmVuY2VzCg==
'''
pack_marky_bib = '''
QGFydGljbGV7TXVsbGVyMTk5MywKICAgIGF1dGhvciAgPSB7UGV0ZXIgTXVsbGVyfSwKICAg
IHRpdGxlICAgPSB7VGhlIHRpdGxlIG9mIHRoZSB3b3JrfSwKICAgIGpvdXJuYWwgPSB7VGhl
IG5hbWUgb2YgdGhlIGpvdXJuYWx9LAogICAgeWVhciAgICA9IHsxOTkzfSwKICAgIG51bWJl
ciAgPSB7Mn0sCiAgICBwYWdlcyAgID0gezIwMS0yMTN9LAogICAgbW9udGggICA9IHs3fSwK
ICAgIG5vdGUgICAgPSB7QW4gb3B0aW9uYWwgbm90ZX0sCiAgICB2b2x1bWUgID0gezR9Cn0K
'''
pack__gitignore = '''
YnVpbGQvCmh0bWwvCg==
'''

###!!!:::marky_pack_data:::!!!###
########################################################################
# SECTION IS AUTO-PACKAGED USING ./marky.py --pack --force
########################################################################

########################################################################

def _marky_front_join(y, text):
	return """---\n%s\n---\n%s""" % (
		yaml.dump(y, allow_unicode=True, default_flow_style=False),
		text
	)

def _marky_front_split(t):
	global _MARKY_EXEC_DICT
	if not t.startswith("---\n"):
		return dict(), mark, 0
	y = t.split("---\n")[1]
	meta_lines = len(y.split("\n")) + 2
	mark = "---\n".join(t.split("---\n")[2:])
	print("---\n" + y + "---", flush=True)
	data = dict()
	try:
		data = yaml.safe_load(y)
	except Exception as ex:
		print("# YAML ERROR", type(ex), str(ex))
		sys.exit(1)
	return data, mark, meta_lines

########################################################################

def _marky_mdtext_print(*args, sep=" ", shift="", crop=False, ret=False):
	global _MARKY_EXEC_QUIET
	global _MARKY_EXEC_TEXT
	global _MARKY_EXEC_APPEND
	if len(args) == 0:
		if _MARKY_EXEC_APPEND == False: _MARKY_EXEC_TEXT.append("")
		_MARKY_EXEC_APPEND = False
	else:
		if ret: return _marky_mdtext_ret(args[0], shift, crop)
		if crop or shift != "":
			_marky_mdtext_crop(args[0], shift, crop)
			if args[-1] == _marky_mdtext_print:
				_MARKY_EXEC_APPEND = True
			return
		exec_append_new = False
		if args[-1] == _marky_mdtext_print:
			exec_append_new = True
			args = args[0:-1]
		text = sep.join([str(i) for i in args])
		if _MARKY_EXEC_APPEND and len(_MARKY_EXEC_TEXT) > 0:
			_MARKY_EXEC_TEXT[-1] += text
		else:
			_MARKY_EXEC_TEXT.append(text)
		_MARKY_EXEC_APPEND = exec_append_new
		if not _MARKY_EXEC_QUIET: print(text, end="" if _MARKY_EXEC_APPEND else "\n", flush=True)

def _marky_mdtext_crop(arg, shift, crop):
	global _MARKY_EXEC_TEXT
	global _MARKY_EXEC_APPEND
	if not type(arg) is str:
		arg = str(arg)
	arg = arg.split("\n")
	if crop:
		if len(arg[0].strip()) == 0:
			arg = arg[1:]
		if len(arg[-1].strip()) == 0:
			arg = arg[:-1]
	n = len(arg[0]) - len(arg[0].lstrip())
	for i in arg:
		if crop and len(i[0:n].lstrip()) == 0:
			i = i[n:]
		_MARKY_EXEC_TEXT.append(shift + i)

def _marky_mdtext_ret(arg, shift="", crop=True):
	if not type(arg) is str:
		arg = str(arg)
	text = []
	arg = arg.split("\n")
	if crop:
		if len(arg[0].strip()) == 0:
			arg = arg[1:]
		if len(arg[-1].strip()) == 0:
			arg = arg[:-1]
	n = len(arg[0]) - len(arg[0].lstrip())
	for i in arg:
		if crop and len(i[0:n].lstrip()) == 0:
			i = i[n:]
		text.append(shift + i)
	return "\n".join(text)

########################################################################

class _marky_fmtcall:
	def __init__(self, name, fmtc):
		self.name = name
		self.fmtc = fmtc
	def __call__(self, *args, **kwargs):
		text = "<<?html "
		f = getattr(self.fmtc.html, self.name)
		if callable(f):
			v = f(*args, **kwargs)
			if type(v) is str: text += v
		elif type(f) is str:
			text += f.format(*args, **kwargs)
		text += " html?>>"
		text += "<<?pdf "
		f = getattr(self.fmtc.pdf, self.name)
		if callable(f):
			v = f(*args, **kwargs)
			if type(v) is str: text += v
		elif type(f) is str:
			text += f.format(*args, **kwargs)
		text += " pdf?>>"
		return text

class _marky_fmtcode:
	def __init__(self, pdf=None, html=None):
		if not html is None: self.html = html
		if not pdf is None: self.pdf = pdf
	def __call__(self, *args, **kwargs):
		text = "<<?html "
		f = self.html
		if callable(f):
			v = f(*args, **kwargs)
			if type(v) is str: text += v
		elif type(f) is str:
			text += f.format(*args, **kwargs)
		text += " html?>>"
		text += "<<?pdf "
		f = self.pdf
		if callable(f):
			v = f(*args, **kwargs)
			if type(v) is str: text += v
		elif type(f) is str:
			text += f.format(*args, **kwargs)
		text += " pdf?>>"
		return text
	def __getattr__(self, name):
		return _marky_fmtcall(name, self)

########################################################################

def _marky_rebrace(t):
	t = t.replace("{{", "<<brace?")
	t = t.replace("}}", "?brace>>")
	t = t.replace("{", "{{")
	t = t.replace("}", "}}")
	t = t.replace("<<brace?", "{")
	t = t.replace("?brace>>", "}")
	return t

def _marky_code_text(t, fstring=True):
	if fstring:
		if not '"""' in t and not t.endswith('"'):
			return '___(rf"""' + _marky_rebrace(t) + '""", ___); '
		elif not "'''" in t and not t.endswith("'"):
			return "___(rf'''" + _marky_rebrace(t) + "''', ___); "
		else:
			print("# ERROR", "python code contains \"\"\" as well as '''.")
			sys.exit(1)
	else:
		if not '"""' in t and not t.endswith('"'):
			return '___(r"""' + t + '""", ___); '
		elif not "'''" in t and not t.endswith("'"):
			return "___(r'''" + t + "''', ___); "
		else:
			print("# ERROR", "python code contains \"\"\" as well as '''.")
			sys.exit(1)

def _marky_paste_code(t):
	show_code = False
	if t.startswith("!"):
		t = t[1:]
		show_code = True
	if show_code:
		return _marky_code_text(t, fstring=False) + t
	return t

def _marky_meta_merge(old, front):
	meta = {}
	meta.update(old)
	try:
		for k, v in front.items():
			if k in meta:
				print("<!-- field exists, skip yaml %s --!>" % k)
			else:
				meta[k] = v
	except Exception as ex:
		print("# META MERGE ERROR", type(ex), str(ex))
		sys.exit(1)
	return meta

def _marky_run(fname, meta, inbase):
	global _MARKY_EXEC_DICT
	with open(fname, "r") as h:
		front, t, meta_lines = _marky_front_split(h.read())
	meta = _marky_meta_merge(meta, front)
	p = 0
	r = ""
	while True:
		p0 = t.find("<?", p)
		if p0 > -1:
			if p0 > 0: r += _marky_code_text(t[p:p0])
			p1 = t.find("?>", p0)
			if p1 > -1:
				code = t[p0+2:p1]
				r += _marky_paste_code(code)
				p = p1 + 2
			else:
				print("# ERROR", "missing ?>")
				sys.exit(1)
		else:
			r += _marky_code_text(t[p:])
			break
	for a, b, c, count in [
		("", "<%s?", "", 1),
		("", "?%s>", "", 1),
		("", "{%s", "{", 3),
		("}", "%s}", "", 3)
	]:
		for j in reversed(range(1, count+1)):
			for i in range(3):
				X = "\\"*(i + 1)
				Y = "\\"*(i + 0)
				r = r.replace(a + (b % X)*j + c, a + (b % Y)*j + c)
	open(_MARKY_BUILD_DIR + inbase + ".py", "w").write(r)
	try:
		exec(r, _MARKY_EXEC_DICT, None)
	except Exception as ex:
		_marky_print_trace(ex, meta_lines, t)
		sys.exit(1)
	return meta

def _marky_print_trace(ex, mlines, code):
	print("# TRACEBACK")
	import traceback
	traceback.print_tb(ex.__traceback__)
	print("# PYTHON ERROR")
	print(type(ex), str(ex))
	if ex.filename == "<string>":
		print("# ERROR LOCATION")
		code = code.split("\n")
		for i in range(max(0, ex.lineno-5), min(len(code), ex.lineno+5)):
			print("*" if i + 1 == ex.lineno else " ", "%03d" % i, code[i])

########################################################################

def _marky_meta_link(front, link):
	flink = {}
	try:
		for k, v in front.items():
			if "--" in k: continue
			if not k in flink:
				flink[k] = v
			else:
				print("<!-- field exists, skip yaml %s --!>" % k)
		for k, v in front.items():
			if not "--" in k: continue
			x = k.split("--")
			if x[-1] in _MARKY_FORMAT:
				if x[-1] == link:
					k = "--".join(x[0:-1])
					if k in flink:
						print("<!-- field link, merge yaml %s --!>" % k)
						if type(v) is list: flink[k].extend(v)
						if type(v) is dict: flink[k].update(v)
						if type(v) is str: flink[k] += " " + v
						else: flink[k] = v
					else:
						print("<!-- field link, set yaml %s --!>" % k)
						flink[k] = v
	except Exception as ex:
		print("# META LINK ERROR", type(ex), str(ex))
		sys.exit(1)
	return flink

def _marky_link(front, md_text, link):
	md_text = md_text.replace(".???", "." + link)
	md_text = md_text.replace(r".\???", r".???")
	md_text = md_text.replace(r".\\???", r".\???")
	lsep = 3
	len_args = len(link) + 1
	c = 0
	newtext = ""
	p = md_text.find("<<?")
	while p >= 0:
		q = md_text.find("?>>", p + lsep)
		if q > 0:
			newtext += md_text[c:p]
			expr = md_text[p+lsep:q]
			if expr.startswith(link) and expr.endswith(link):
				newtext += expr[len_args:-len_args]
			c = q + lsep
			p = md_text.find("<<?", c)
		else:
			p = md_text.find("<<?", p + lsep)
	newtext += md_text[c:]
	flink = _marky_meta_link(front, link)
	return _marky_front_join(flink, newtext)

def _marky_write_build(inbase, outdir, front, mark):
	os.makedirs(_MARKY_BUILD_DIR + outdir, exist_ok=True)
	if not mark is None:
		open(_MARKY_BUILD_DIR + inbase + ".md", "w").write(_marky_front_join(front, mark))
		for fmt in _MARKY_FORMAT:
			open(_MARKY_BUILD_DIR + inbase + "." + fmt + ".md", "w").write(_marky_link(front, mark, fmt))

	with open(_MARKY_BUILD_DIR + inbase + ".make", "w") as fhnd:
		fhnd.write(f"""# auto-generated
all_md:=$(all_md) {_MARKY_MD_DIR+inbase}.md

{_MARKY_BUILD_DIR+inbase}.md: {_MARKY_MD_DIR+inbase}.md
	mkdir -p "{_MARKY_BUILD_DIR+outdir}"
	ln -snf ../{_MARKY_DATA_DIR} {_MARKY_BUILD_DIR+_MARKY_DATA_DIR}
	./marky.py --base="{inbase}.md"

.PHONY: build/{inbase}
build/{inbase}: {_MARKY_BUILD_DIR+inbase}.md

all_build:=$(all_build) build/{inbase}
"""
		)
		if "pdf" in _MARKY_FORMAT:
			fhnd.write(f"""
{_MARKY_BUILD_DIR+inbase}.tex: {_MARKY_BUILD_DIR+inbase}.pdf.md {_MARKY_MD_DIR+inbase}.md
	mkdir -p "{_MARKY_BUILD_DIR+outdir}"
	./pandoc-run tex {_MARKY_BUILD_DIR+inbase}.pdf.md {_MARKY_BUILD_DIR+inbase}.tex

all_tex:=$(all_tex) {_MARKY_BUILD_DIR+inbase}.tex
"""
			)
		for fmt in _MARKY_FORMAT:
			fhnd.write(f"""
{_MARKY_BUILD_DIR+inbase}.{fmt}.md: {_MARKY_BUILD_DIR+inbase}.md

{fmt}/{inbase}.{fmt}: {_MARKY_BUILD_DIR+inbase}.{fmt}.md {_MARKY_MD_DIR+inbase}.md
	mkdir -p "{fmt}/{outdir}"
	./pandoc-run {fmt} {_MARKY_BUILD_DIR+inbase}.{fmt}.md {fmt}/{inbase}.{fmt}

.PHONY: {fmt}/{inbase}
{fmt}/{inbase}: {fmt}/{inbase}.{fmt}

all_{fmt}:=$(all_{fmt}) {fmt}/{inbase}.{fmt}
"""
			)

########################################################################

def _marky_pack_b64enc(x, n=72):
	x = base64.b64encode(bytes(x, "utf-8")).decode("ascii")
	return "\n".join([x[i:i+n] for i in range(0, len(x), n)])

def _marky_pack_b64dec(x):
	return base64.b64decode(bytes(x.replace("\n", ""), "ascii")).decode("utf-8")

def _marky_load_pack(i):
	return _marky_pack_b64dec(eval("pack_" + i.split("/")[-1].replace(".", "_").replace("-", "_")))

def _marky_pack_write_file(fname, force=False):
	if not os.path.exists(fname) or force:
		print("# WRITE", fname)
		open(fname, "w").write(_marky_load_pack("./" + fname))
	else:
		print("# EXISTS", fname)

def _marky_store_pack(i, ftext):
	return "pack_%s = '''\n%s\n'''\n" % (i.split("/")[-1].replace(".", "_").replace("-", "_"), _marky_pack_b64enc(ftext))

def _marky_pack_read_file(fname):
	return _marky_store_pack("./" + fname, open(fname, "r").read())

########################################################################

_MARKY_FORMAT = ["html", "pdf"]
_MARKY_BUILD_DIR = "build/"  #< WITH trailing /
_MARKY_MD_DIR = "md/"  #< WITH trailing /
_MARKY_DATA_DIR = "data" #< no trailing /
_MARKY_PACK_DIRS = [
	_MARKY_BUILD_DIR,
	_MARKY_DATA_DIR,
	_MARKY_MD_DIR
]
_MARKY_PACK_FILES = [
	"Makefile",
	"pandoc-run",
	"md/marky.md",
	"data/marky.bib",
	".gitignore"
]
_MARKY_EXEC_QUIET = False
_MARKY_EXEC_DICT = dict()
_MARKY_EXEC_TEXT = list()
_MARKY_EXEC_APPEND = False
_MARKY_EXEC_DICT["___"] = _marky_mdtext_print
_MARKY_EXEC_DICT["fmtcode"] = _marky_fmtcode

########################################################################

if __name__ == "__main__":

	parser = argparse.ArgumentParser(add_help=False)

	parser.add_argument("--version", action='store_true', help="version is v" + ".".join([str(i) for i in _MARKY_VERSION]))
	parser.add_argument("--help", action='store_true', help="show this help message")
	parser.add_argument("--base", type=str, default="", help="path to input markdown text")
	parser.add_argument("--init", action='store_true', help="create dirs (" + ", ".join(_MARKY_PACK_DIRS) + ") and files (" + ", ".join(_MARKY_PACK_FILES) + ")")
	parser.add_argument("--force", action='store_true', help="force overwrite of files for --init/--pack")
	parser.add_argument("--pack", action='store_true', help="pack files (" + ", ".join(_MARKY_PACK_FILES) + ") into marky.py.pack source")
	parser.add_argument("--scan", action='store_true', help="create build/*.make from md/*.md")
	parser.add_argument("--quiet", action='store_true', help="do not show Markdown output")

	# ~ args, uargs = parser.parse_known_args()
	args = parser.parse_args()

	sys.path.append(".")

########################################################################

	if args.version:
		print(".".join([str(i) for i in _MARKY_VERSION]))
		sys.exit(0)
	elif args.help or len(sys.argv) == 1:
		parser.print_help()
		sys.exit(0)
	elif args.init:
		for i in _MARKY_PACK_DIRS:
			if not os.path.exists(i):
				print("# MKDIR", i)
				os.mkdir(i)
			else:
				print("# EXISTS", i)
		for i in _MARKY_PACK_FILES:
			_marky_pack_write_file(i, args.force)
		print("# USAGE")
		print("make help")
		sys.exit(0)
	elif args.pack:
		print("# PACK", ", ".join(_MARKY_PACK_FILES))
		marky_text = open(sys.argv[0], "r").read()
		head, src, tail = tuple(marky_text.split("\n###!!!:::marky_pack_data:::!!!###\n"))
		src = "".join([_marky_pack_read_file(i) for i in _MARKY_PACK_FILES])
		marky_text = "\n###!!!:::marky_pack_data:::!!!###\n".join([head, src, tail])
		open(sys.argv[0] + ".pack", "w").write(marky_text)
		if args.force:
			print("# UPDATE OF `marky` FORCED")
			print("# -----------------------")
			print("# mv marky.py.pack marky.py")
			print("# chmod 775 marky.py")
			os.replace("marky.py.pack", "marky.py")
			os.chmod("marky.py", 0o775)
		else:
			print("# MANUAL UPDATE NEEDED")
			print("# --------------------")
			print("mv marky.py.pack marky.py")
			print("chmod +x marky.py")
		sys.exit(0)
	elif args.scan:
		for i in glob.glob("md/**/*.md", recursive=True):
			inbase = i[3:-3]
			outdir = "/".join(inbase.split("/")[0:-1])
			print("# WRITE", _MARKY_BUILD_DIR + inbase + ".make")
			_marky_write_build(inbase, outdir, None, None)
		sys.exit(0)
		pass
	elif args.force:
		print("# ERROR", "--force can only be used with --pack/--init")
		sys.exit(1)
	elif args.quiet:
		_MARKY_EXEC_QUIET = True

########################################################################

	infile = _MARKY_MD_DIR + args.base
	if len(args.base) == 0:
		print("# ERROR", "empty base: use --base file.md")
		sys.exit(1)
	if not os.path.exists(infile):
		print("# ERROR", "wrong base %s: file not found %s" % (args.base, infile))
		sys.exit(1)
	inbase = args.base if not "." in args.base.split("/")[-1] else ".".join(args.base.split(".")[0:-1])
	outdir = "/".join(inbase.split("/")[0:-1])

	if os.path.exists(_MARKY_BUILD_DIR):
		front = _marky_run(infile, {}, inbase)
		mark = "\n".join(_MARKY_EXEC_TEXT)
		_marky_write_build(inbase, outdir, front, mark)
	else:
		print("# ERROR", "no build dir: mkdir build")
		sys.sys.exit(1)
