#!/bin/bash

cd $(dirname $0)
mkdir -p fmtplotjs
cd fmtplotjs && \
for i in                                                            \
https://www.flotcharts.org/flot/lib/jquery.event.drag.js            \
https://www.flotcharts.org/flot/lib/jquery.mousewheel.js            \
https://www.flotcharts.org/flot/source/jquery.js                    \
https://www.flotcharts.org/flot/source/jquery.canvaswrapper.js      \
https://www.flotcharts.org/flot/source/jquery.colorhelpers.js       \
https://www.flotcharts.org/flot/source/jquery.flot.js               \
https://www.flotcharts.org/flot/source/jquery.flot.saturated.js     \
https://www.flotcharts.org/flot/source/jquery.flot.browser.js       \
https://www.flotcharts.org/flot/source/jquery.flot.drawSeries.js    \
https://www.flotcharts.org/flot/source/jquery.flot.uiConstants.js   \
https://www.flotcharts.org/flot/source/jquery.flot.resize.js        \
https://www.flotcharts.org/flot/source/jquery.flot.legend.js        \
https://www.flotcharts.org/flot/source/jquery.flot.navigate.js      \
https://www.flotcharts.org/flot/source/jquery.flot.hover.js         \
https://www.flotcharts.org/flot/source/jquery.flot.touch.js         \
https://www.flotcharts.org/flot/source/jquery.flot.touchNavigate.js \
https://www.flotcharts.org/flot/source/jquery.flot.selection.js     \
https://www.flotcharts.org/flot/source/jquery.flot.symbol.js        \
https://www.flotcharts.org/flot/source/jquery.flot.image.js         \
#
do

[ ! -e $(basename $i) ] && wget $i

done
